<?php

class KnownFilters {

    public $fields = array(
        "name",
        "email",
        "url",
        "website",
        "range-limit",
        "plain-text",
        "regex",
        "pattern",
        "bbcode",
        "markdown",
        "wiki",
        "phone-carrier",
        "phone-number",
        "credit-card",
        "credit-card-cvv",
        "credit-card-date",
        "street-address",
        "city-address",
        "state-address",
        "zipcode-address",
        "microsoft",
        "google",
        "youtube",
        "facebook",
        "twitter"
     );

}

?>